# Generated by Django 5.0.6 on 2024-05-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(upload_to='recipes_image'),
        ),
    ]
