# Generated by Django 5.0.6 on 2024-05-22 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 5, 22, 23, 38, 37, 315670, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
