# Generated by Django 5.0.6 on 2024-05-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car_delete_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
