# Generated by Django 5.0.6 on 2024-05-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0004_alter_reportcard_date_of_report_card_generation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank',)},
        ),
    ]
