# Generated by Django 5.0.6 on 2024-05-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0005_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
